# name: Build KarigAI APK
# on: [push, workflow_dispatch]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
      
#       - uses: subosito/flutter-action@v2
#         with:
#           channel: 'stable'
          
#       - name: The Nuclear Dependency Fix
#         working-directory: karigai_mobile
#         run: |
#           # 1. Ziddi lock file ko delete karna
#           rm -f pubspec.lock
          
#           # 2. Missing package add karna
#           flutter pub add audioplayers
          
#           # 3. Zabardasti naya version code me daalna
#           echo "" >> pubspec.yaml
#           echo "dependency_overrides:" >> pubspec.yaml
#           echo "  record_linux: ^1.3.0" >> pubspec.yaml
          
#           # 4. Naye packages refresh karna
#           flutter pub get
        
#       - name: Build APK
#         working-directory: karigai_mobile
#         run: flutter build apk --release -t ${{ github.workspace }}/karigai_backend/ml_models/models/colab_models/Secondary_Frontend/main.dart
        
#       - name: Upload APK
#         uses: actions/upload-artifact@v4
#         with:
#           name: KarigAI-App-Release
#           path: karigai_mobile/build/app/outputs/flutter-apk/app-release.apk







name: Build KarigAI APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: The Nuclear Dependency Fix
        working-directory: karigai_mobile
        run: |
          rm -f pubspec.lock
          flutter pub add audioplayers
          echo "" >> pubspec.yaml
          echo "dependency_overrides:" >> pubspec.yaml
          echo "  record_linux: ^1.3.0" >> pubspec.yaml
          flutter pub get
          
      # 🔥 YAHAN MAINE GRADLE REPAIR WAPAS ADD KAR DIYA HAI
      - name: Repair Android Setup
        working-directory: karigai_mobile
        run: flutter create --platforms=android .
        
      - name: Build APK
        working-directory: karigai_mobile
        run: flutter build apk --release -t ${{ github.workspace }}/karigai_backend/ml_models/models/colab_models/Secondary_Frontend/main.dart
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: KarigAI-App-Release
          path: karigai_mobile/build/app/outputs/flutter-apk/app-release.apk
