name: Build KarigAI APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      # 🔥 Yahan hum missing packages daal rahe hain aur purane crash wale package ko force-fix kar rahe hain
      - name: Force Fix Dependencies
        working-directory: karigai_mobile
        run: |
          flutter pub add audioplayers
          flutter pub add "record_linux:^1.3.0"
          flutter pub get
        
      - name: Build APK
        working-directory: karigai_mobile
        run: flutter build apk --release -t ${{ github.workspace }}/karigai_backend/ml_models/models/colab_models/Secondary_Frontend/main.dart
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: KarigAI-App-Release
          path: karigai_mobile/build/app/outputs/flutter-apk/app-release.apk
